CREATE OR REPLACE FUNCTION test_error() RETURNS VOID AS $FUNCTION$
DECLARE
BEGIN
  --RAISE SQLSTATE 'U0001' USING MESSAGE = 'stored function error'; 
  RAISE SQLSTATE 'U0001';
END;
$FUNCTION$ LANGUAGE plpgsql;
